language: scala
scala:
   - 2.11.2

sudo: required
services:
  - docker

env:
  global:
    - SPARK_HOME=./spark

matrix:
  fast_finish: true
  include:
  - scala: 2.11.2
    script:
      - ./scripts/wait-for-it.sh 127.0.0.1:9042 -- echo "Cassandra/ScyllaDB is up"
      - ./sbt test

  - scala: 2.11.2
    env: INTEGRATION_TESTS=true
    install:
      - make build
    script:
      - ./scripts/get_apache_spark.sh "2.2.0" "2.7" || travis_terminate 1
      - sleep 10 # wait for it doesn't work, port is avalable but scyllaDB is still down
      - ./hash src/test/resources/siva || travis_terminate 1
      - ./query ./LICENSE
      - ./report
    deploy:
      - provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file_glob: true
        file:
          - "target/*.jar"
          - hash
          - query
          - report
        skip_cleanup: true
        on:
          tags: true
      - provider: script
        script: make docker-push-latest
        on:
          tags: true
      - provider: script
        script: make docker-push
        on:
          branch: experimental

  - scala: 2.11.2
    env: STYLE_CHECK=true
    script: ./sbt scalastyle

before_script:
 - ./scripts/start_docker.sh

after_failure:
 - docker logs db

cache:
  directories:
    - .spark-dist
    - /home/travis/.sbt
    - /home/travis/.ivy2
