language: scala
scala:
   - 2.11.2

sudo: required
services:
  - docker

matrix:
  fast_finish: true
  include:
  - scala: 2.11.2
    script: ./sbt test

  - scala: 2.11.2
    env: INTEGRATION_TESTS=true
    script:
     - ./hash .
     - ./query ./LICENSE

  - scala: 2.11.2
    env: STYLE_CHECK=true
    script: ./sbt scalastyle

before_script:
 - ./scripts/start_docker.sh

after_failure:
 - docker logs db

cache:
  directories:
    - /home/travis/.sbt
    - /home/travis/.ivy2
