language: scala
scala:
   - 2.11.2

sudo: required
services:
  - docker

env:
  global:
    - SPARK_HOME=./spark

matrix:
  fast_finish: true
  include:
  - scala: 2.11.2
    script:
      - sleep 10 # wait for it doesn't work, port is avalable but scyllaDB is still down
      - ./sbt test

  - scala: 2.11.2
    env: INTEGRATION_TESTS=true
    install:
      - make build
    script:
      - ./scripts/get_apache_spark.sh "2.2.0" "2.7" || travis_terminate 1
      - sleep 10 # wait for it doesn't work, port is avalable but scyllaDB is still down
      - ./hash src/test/resources/siva || travis_terminate 1
      - ./query ./LICENSE
      - ./report
    before_deploy:
      # the list is quite huge, but we will improve it later
      - mkdir -p gemini-$TRAVIS_TAG/target
      - mkdir -p gemini-$TRAVIS_TAG/project
      - mkdir -p gemini-$TRAVIS_TAG/src/main/resources
      - cp target/*.jar gemini-$TRAVIS_TAG/target/
      - cp sbt gemini-$TRAVIS_TAG/
      - cp build.sbt gemini-$TRAVIS_TAG/
      - cp hash gemini-$TRAVIS_TAG/
      - cp query gemini-$TRAVIS_TAG/
      - cp report gemini-$TRAVIS_TAG/
      - cp project/build.properties gemini-$TRAVIS_TAG/project/
      - cp project/Dependencies.scala gemini-$TRAVIS_TAG/project/
      - cp project/plugins.sbt gemini-$TRAVIS_TAG/project/
      - cp -r src/main/resources/* gemini-$TRAVIS_TAG/src/main/resources/
      - tar -cvzf gemini_$TRAVIS_TAG.tar.gz gemini-$TRAVIS_TAG/
    deploy:
      - provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        file_glob: true
        file: gemini_$TRAVIS_TAG.tar.gz
        skip_cleanup: true
        on:
          tags: true
      - provider: script
        script: make docker-push-latest
        on:
          tags: true
      - provider: script
        script: make docker-push
        on:
          branch: experimental

  - scala: 2.11.2
    env: STYLE_CHECK=true
    script: ./sbt scalastyle

before_script:
 - ./scripts/start_docker.sh

after_failure:
 - docker logs db

cache:
  directories:
    - .spark-dist
    - /home/travis/.sbt
    - /home/travis/.ivy2
