language: scala
scala:
   - 2.11.2

sudo: required
services:
  - docker

matrix:
  fast_finish: true
  include:
  - scala: 2.11.2
    script: ./sbt test

  - scala: 2.11.2
    env: INTEGRATION_TESTS=true
    script: ./hash .; ./query ./LICENSE

  - scala: 2.11.2
    env: STYLE_CHECK=true
    script: ./sbt scalastyle

before_script:
 - docker run -p 9042:9042 -d scylladb/scylla:2.0.0 --broadcast-address 127.0.0.1 --listen-address 0.0.0.0 --broadcast-rpc-address 127.0.0.1 --memory 2G --smp 1

cache:
  directories:
    - /home/travis/.sbt